name: Run Tests

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  RunTestingBattery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pytest and dependencies
        run: |
          pip install pytest pytest-spec pytest-describe
          pip install pytest-mock # Install pytest-mock for mocking in testing
      - name: Run pytest for TestingDouble
        run: pytest --spec --color=yes test_battery.py

  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: pip install behave behave-webdriver
      - name: Run behave
        run: behave
